//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamMessenger.Client.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TeamMessenger.Client.Shared.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By clicking the &quot;Connect&quot; button, you confirm that you accept .
        /// </summary>
        public static string AcceptTOS1 {
            get {
                return ResourceManager.GetString("AcceptTOS1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms Of Service.
        /// </summary>
        public static string AcceptTOS2 {
            get {
                return ResourceManager.GetString("AcceptTOS2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are connected as.
        /// </summary>
        public static string ConntectedAs {
            get {
                return ResourceManager.GetString("ConntectedAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrupted Message.
        /// </summary>
        public static string CorruptedMessage {
            get {
                return ResourceManager.GetString("CorruptedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new.
        /// </summary>
        public static string CreateNewGroupSecret {
            get {
                return ResourceManager.GetString("CreateNewGroupSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new.
        /// </summary>
        public static string CreateNewPersonalSecret {
            get {
                return ResourceManager.GetString("CreateNewPersonalSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        public static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter message.
        /// </summary>
        public static string EnterMessage {
            get {
                return ResourceManager.GetString("EnterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group ID.
        /// </summary>
        public static string GroupId {
            get {
                return ResourceManager.GetString("GroupId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group secret.
        /// </summary>
        public static string GroupSecret {
            get {
                return ResourceManager.GetString("GroupSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TeamMessenger.
        /// </summary>
        public static string MessageExchange {
            get {
                return ResourceManager.GetString("MessageExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No group secret.
        /// </summary>
        public static string NoGroupKey {
            get {
                return ResourceManager.GetString("NoGroupKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No personal secret.
        /// </summary>
        public static string NoPersonalKey {
            get {
                return ResourceManager.GetString("NoPersonalKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No username.
        /// </summary>
        public static string NoUsername {
            get {
                return ResourceManager.GetString("NoUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demonstration purposes only!.
        /// </summary>
        public static string OnlyForDemonstration {
            get {
                return ResourceManager.GetString("OnlyForDemonstration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal secret.
        /// </summary>
        public static string PersonalSecret {
            get {
                return ResourceManager.GetString("PersonalSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public key.
        /// </summary>
        public static string PublicKey {
            get {
                return ResourceManager.GetString("PublicKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By accepting these Terms of Use, you confirm that you have not and will not transfer any information from this website, including your Personal Password and Group Password, to any third party and you also confirm that you have not used, will not use, do not allow to use and will not allow to use the Service located on this website for the purposes of information distribution, receipt, transmission, delivery and (or) processing of electronic messages, and any other activities prohibited by the laws and regul [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TOS {
            get {
                return ResourceManager.GetString("TOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
    }
}
